### ISSUE TITLE
Model downloads broken: Update gdown to 4.7.3

### ISSUE THREAD

**Issue by ShoryuKyzan** [hydrusbeta/hay_say_ui#24]
# Problem
controllable_talknet model downloads (at least these) are broken. Error is access denied. 
These use gdown. Update gdown to fix.
See this issue: https://github.com/wkentaro/gdown/issues/292

Other gdown based model downloads likely broken as well.
Manual model installs take alot longer since server restart is required.

# Solution
At a minimum, update gdown to 4.7.3
This line:
https://github.com/hydrusbeta/hay_say_ui/blob/3c86f6c2638a78d8a5a5e00dc0d0ddbc3040ebaf/Dockerfile#L42

# Testing

I've tested 4.7.3 and it works for controllable_talknet model downloads.

**Comment by hydrusbeta** [comment]
Hello @ShoryuKyzan. Thank you so much for bringing this issue to my attention along with its solution. I have updated the appropriate image in the Docker Hub repository so it now uses gdown version 5.2.0 and I verified that it fixes the issue. You can update Hay Say by following the instructions here:
https://github.com/hydrusbeta/hay_say_ui?tab=readme-ov-file#updating-hay-say

Alternatively, You can run a couple of commands to update gdown within the container without needing to redownload the entire image. First, you will need the name of the Hay Say UI container. Start Hay Say and execute the following command:
```
docker container ls
```
Under the "IMAGE" column, one of the rows will have the value "hydrusbeta/hay_say:hay_say_ui". Note the corresponding value under the NAMES columns:
![image](https://github.com/hydrusbeta/hay_say_ui/assets/128447736/76a84e5e-6749-42bc-becb-b44f88831b45)
Now execute the following two commands, replacing "hay_say_ui-hay_say_ui-1" with the name of your container if it is different:
```
docker exec -it hay_say_ui-hay_say_ui-1 python -m pip uninstall gdown
docker exec -it hay_say_ui-hay_say_ui-1 python -m pip install gdown==5.2.0
```
Then, restart Hay Say.
